### ISSUE TITLE
AHG3 recommendation re ISO 19101: move some aspects of 19103 to 19101?

### ISSUE THREAD

**Issue by PeterParslow** [ISO-TC211/StandardsTracker#405]
"It may be sensible to move some aspects of ISO 19103 to ISO 19101, or vice versa."

See TC 211/N 5561 for more details.

CIB Resolution 2021-02 should start the revision of ISO 19103:2015; the scope (N 5563) currently mentions implementing the learnings from AHG3.

**Comment by heidivanparys** [comment]
If anyone has an opinion on this, and a specific proposal on how what aspect should be moved, I'm happy to take it up again.

**Comment by PeterParslow** [comment]
Dipping into the archived GitHub repository that the team used to draft the report, I realise that this sentence was a late addition by me (as the leader). https://github.com/ISO-TC211/NonRelationalDBTech/wiki may not be visible to everyone in this team.

The overall challenge we received from our presenters was that UML isn't the only CSL, and not (in some people's opinion) always the best one.  But that we (TC 211) did have some good approaches that can be used independent of the CSL. (There is then the challenge of how to formally define those things...)

From memory, I think my concern was that if ISO 19103 is to be purely about describing UML as a Conceptual Schema Language, then any "UML independent parts" should be moved elsewhere. On reflection (informed by today's discussion on ISO 19101), I'm not sure that ISO 19101 is the appropriate place to move them to.

By "UML independent parts" I mean most (or all) of the data types.

Perhaps another way of looking at it would be that we have "conceptual schema language independent" parts of the way that we model the world - the General Feature Model & at least some of the data types. And then we have a UML profile (and potentially other CSLs) that we use.

Another candidate for moving or at least making consistent is (purely in my opinion) is Figure 4 in ISO 19103 and Figure D.2 in ISO 19101.

**Comment by heidivanparys** [comment]
[Figure 4 in ISO 19103](http://iso.sparxcloud.com?m=1&o=EC438FC7-34B1-4378-93C9-F1E756A9195A) is (only) there to give an example of a [UML realization](https://www.uml-diagrams.org/realization.html). See also the figure caption, and the text right below the figure. Perhaps we should adjust the figure, so its focus is on a UML realization, instead of showing so many other UML constructs.

![image](https://user-images.githubusercontent.com/11427611/154752463-e53eba4b-f8f4-4ea1-a2f0-fc33c7ed5deb.png)

> From memory, I think my concern was that if ISO 19103 is to be purely about describing UML as a Conceptual Schema Language, then any "UML independent parts" should be moved elsewhere. On reflection (informed by today's discussion on ISO 19101), I'm not sure that ISO 19101 is the appropriate place to move them to.
>
> By "UML independent parts" I mean most (or all) of the data types.

Could it be that this, or at least part of it, is solved already? ISO 19103 (normatively) references [ISO/IEC 11404:2007,
Information technology — General-Purpose Datatypes (GPD)](https://www.iso.org/obp/ui#iso:std:iso-iec:11404:ed-2:v1:en) (available from http://standards.iso.org/ittf/PubliclyAvailableStandards/c039479_ISO_IEC_11404_2007(E).zip) and refers to it many times in the clause on the data types. So the UML independent data type definitions are in ISO/IEC 11404, aren't they?

> ISO/IEC 11404 is used for formal description of conceptual datatypes in binding (or binding-independent) standards and used as formalization of metadata for data elements, data element concepts, and value domains (see ISO/IEC 11179-3).

As for XML (GML, RDF/XML, etc.):

from https://www.w3.org/TR/xmlschema-2/#typesystem:  

> The framework has been influenced by the [[ISO 11404]](https://www.w3.org/TR/xmlschema-2/#ISO11404) standard on language-independent datatypes

from ISO/IEC 11404:2007:

> Incorporation of latest technologies. Provide enhancements to the use of ISO/IEC 11404 as a datatype nomenclature reference for current programming languages, interface languages and data representation languages, specifically Java, IDL, Express, and XML.

**Comment by PeterParslow** [comment]
"[Figure 4 in ISO 19103](http://iso.sparxcloud.com/?m=1&o=EC438FC7-34B1-4378-93C9-F1E756A9195A) is (only) there to give an example of a [UML realization](https://www.uml-diagrams.org/realization.html)."

I accept that the caption & placement of Figure 3 indicates that it is an example of realization - but also an illustration of 'different levels of abstraction'. But I think in practice it is far more useful than that. Perhaps a modernise/corrected/revised version of Figure 3 should find its home elsewhere? ISO 19101 Annex D?

I'm all for simply importing types from ISO/IEC 11404 if they are fit for our purpose.

**Comment by heidivanparys** [comment]
ISO/FDIS 19103 elaborates on "level of abstraction", it has updated figures on realization, and the relation to ISO/IEC 11404 has been described in much more detail. Therefore at least the 19103 label can be removed from this issue.

**Comment by JanHjelmager** [comment]
As the issue have been handled in the revision of ISO 19103 the issue is closed.
