### ISSUE TITLE
considerations on update of polymorphism definition

### ISSUE THREAD

**Issue by ReesePlews** [ISO-TC211/StandardsTracker#461]
polymorphism (defined by 19139-1:2019, 3.3) https://isotc211.geolexica.org/concepts/840/ was sourced some years back from a tech web site. while updated once before, the current source reference URL still does not directly resolve to a glossary page. a search on the site resolves to [https://www.techtarget.com/whatis/definition/polymorphism](url)

the best option would be to find a suitable iso/iec replacement for this definition. if an iso/iec replacement definition cannot be found, perhaps another definition can be found with a more stable source reference or we should just edit up our own definition, which would solve the source reference issue.

this ticket opened in regards to comments received on 19115-3 DIS from DE and UK via personal communication XMG convenor Evert @ejbleys

**Comment by PeterParslow** [comment]
ISO 19139-1 Clause 6.6 discusses polymorphism describing how the definition in 3.3 is actually used in the document - which is more about data (whereas the "techtarget" definition is more about software). After that, the term is actually only used once in the rest of ISO 19139-1, at 7.2.3.2 b). Even the original ISO 19139:2016 didn't make much use of the term. (The use in 19139:2016 to support multi-lingualism has been moved to ISO 19115-3)

That said, I wonder why we (the ISO 19139-1 team) didn't spot the ISO/IEC 18023-1:2006, 3.1.13 definition of polymorphism, which is specifically about data & therefore seems more relevant to ISO 19139:

"technique where alternate representations of the same data serve different needs"

For interest: UML Superstructure 2.4.1 (ISO/IEC 19505-2) uses the term polymorphism (once) without defining it - presumably believing it to be a well known term in the IT/programming community: which I believe it is.

**Comment by ReesePlews** [comment]
@PeterParslow thank you for the update. ISO 18023-1 entry was probably buried under all of those bio-chem related entries...  i have forwarded your suggestion to Evert.  as 19115-3 is in DIS now, i am not sure what Evert wants to do.  it may be better to just wait and flag it for the terminology PWI and deal with it at the 19139-1 revision.

**Comment by JanHjelmager** [comment]
Before changing the definition we have to make sure that the new definition does conflict with other use in the 19100 suite of standards. If you look at the screenshot below you can see that 1917 might have an issue.

![image](https://user-images.githubusercontent.com/40292830/175507777-055a74f9-92df-480f-bfc8-0303794ca086.png)

**Comment by JanHjelmager** [comment]
@ReesePlews given that the term is not defined in 19107 and only used once I agree with you. So as soon as Evert and the PT have agreed on a solution I suppose we can close the issue.

**Comment by ReesePlews** [comment]
@JanHjelmager is there anyway to keep this open for future reference? if it is closed can we still see it, or do we need to search the closed tickets? it would be good to revisit this in the Terminology PWI. i can make an external note if this is a problem here. thanks.

**Comment by ronaldtse** [comment]
Perhaps the ISO/IEC 18023 definition is appropriate, it seems to define it as a "technique" instead of a "characteristic" though.

<img width="636" alt="Screenshot 2022-06-27 at 11 00 47 AM" src="https://user-images.githubusercontent.com/11865/175846376-fea0a6a2-7255-4b44-967d-83172bca2880.png">

vs

ISO/TS 19139-1:2019
"characteristic of being able to assign a different meaning or usage to something in different contexts — specifically, to allow an entity such as a variable, a function, or an object to have more than one form"

The 3 instances in 19115-3 of it are as follows.

> === Multilingual adaptability and polymorphism
> 
> Cultural and linguistic adaptability is a requirement for metadata
> elements with text content. In <<ISO_19115-1_2014,clause="Annex F">>,
> there is an informative discussion of multilingual textual metadata
> elements. In order to enable the interoperability of multilingual
> instance documents, the XML implementation for this document follows
> the implementation specified in <<ISO-TS_19139-1_2019>>...
> 
> Such **_polymorphism_** allows user communities to modify geographic metadata to meet
> their organizational needs. This pattern is used to provide cultural and
> linguistic adaptability support through metadata instance documents containing
> content in one or more languages that do not violate cardinality rules defined
> in ISO 19115-1 or ISO 19115-2. The lan namespace defines a CharacterString
> property type that includes a CharacterString value, and zero to many
> PT_FreeText elements, each of which is a language-localized character string
> that may be included inline or by reference. Using this extension, a single
> metadata document may include content strings in a variety of languages, but
> clients that are not programmed for multilingual content will still work because
> the standard CharacterString element is present.
> 
> Another example of **_polymorphism_** is the name attribute of type CharacterString
> in the CI_Individual class in ISO 19115-1; if a more structured representation
> is required (e.g. first, middle, and last name elements), **_polymorphism_**
> allows extension of the name element implementation in a user-defined
> namespace that may be substituted for CharacterString within a metadata
> instance. These extensions will be understandable to users who recognize
> the extension namespace, but in general such extensions will not interoperate
> with client software not designed to work with them.

Would "characteristic" apply better to the context of 19115-3?

**Comment by heidivanparys** [comment]
Some more possible definitions:

From [The quarks of object-oriented development](https://scholar.google.com/scholar?q=%22The+quarks+of+object-oriented+development%22), a paper that seems to have quite some citations:
_the ability of different classes to respond to the same message and each implement the method appropriately_

A search on [IGI Global](https://www.igi-global.com/dictionary/polymorphism/22975) also returns some definitions, including references. E.g.

_The ability of object oriented programs to have multiple implementations of the same method name in different classes in an inheritance tree. Derived classes can override the functionality defined in their base class._
(see also https://www.igi-global.com/chapter/business-model-application-uml-stereotypes/13613)

**Comment by ronaldtse** [comment]
This issue was raised again at our 19115-3 EC pre-meeting.

It seems clear that right now there is no "perfect" definition of "polymorphism" that can be sourced from ISO/IEC.

I'll attempt to combine the two next best options:
* ISO/IEC 18023 for "representational polymorphism"
    * "technique where alternate representations of the same data serve different needs"
* ISO/TS 19139 for "polymorphism"
    *  "characteristic of being able to assign a different meaning or usage to something in different contexts - specifically, to allow an entity such as a variable, a function, or an object to have more than one form"
    * Note to entry: There are several different kinds of polymorphism

Changes to be made to ISO/IEC 18023 "representational polymorphism"
* It is about "representational polymorphism", that's why the "alternative representations of" phrase was used in the definition.
* We need a more generic definition for "polymorphism", so we can generalize the "alternative representations of" into "alternative forms of".
* As per the discussions above, it was generally agreed that polymorphism is considered more of a "characteristic" (or "ability") than over "technique".
* in "where ... of the same data ... " the phrase "the same data" is actually the subject of polymorphism. It also defines the term's subject as "data". We can reword it using passive voice: "characteristic of data where alternate forms serve different needs"
* we get => "characteristic of data where alternate forms serve different needs"

Changes to ISO/TS 19139 "polymorphism"
* the text from "specifically, ..." is further specification and does not need to be part of the definition. It can become a note.
* the "Note to entry" can also be kept.
* "assign ... to something in ..." the "something" refers to the thing that is polymorphic. We can get rid of this reference by just using passive voice "characteristic of being able to be assigned a different meaning or usage in different contexts"
* we get => "characteristic of being able to be assigned a different meaning or usage in different contexts"

Considerations:
* I'm not sure if polymorphism only applies to data or to a broader class.
* We need to decide whether polymorphism is about "different forms" and/or "different meaning"
    * "different forms" is clearly a part of polymorphism (word roots)
    * "assigned different meaning" is the reason of "different forms", but it is not dependent on the "different forms". I can have two different classes that mean different things that can be read from the same data. However, "polymorphism" requires "different forms".
    * It seems that it should be "different forms for assigning different meaning".
* While it is important for polymorphism to "serve different needs" (18023) or "usage in different contexts" (19139), "fulfilling needs" is technically a goal to be achieved using "polymorphism", it should not a part of the definition itself. (e.g. the definition of a football should not include "to be scored into the goal")

Combining and slightly massaging them:
* => "characteristic of alternative forms facilitating differentiated interpretation"

Would something like this work?

**Comment by PeterParslow** [comment]
Couple of thoughts:

- I (we?) know that polymorphism can be applied to things other than data; what we need to decide is whether we do that in the context of ISO/TC 211 & specifically ISO 19115. Given that ISO 19115 is only about (meta)data, I think that the scope of polymorphism for ISO 19115 is data. For example, I don't think the use of polymorphism to describe software is required in the definition in ISO 19115
- I am a bit concerned about the idea of polymorphism being intended to facilitate different interpretations of the data. That sounds to me like the issue which arises when a term (label) is used for two different concepts, which I think is something else entirely. In English (where it happens often!) the terms are called "homonyms". I believe we want to use polymorphism for the situation where the data (about a concept/thing/feature instance/...) can be expressed in different ways for different purposes. But all those ways should be recognisably about the same 'thing' - they should be interpreted the same. At present, the term "polymorphism" is only used in ISO 19115-3 in the context of multilingual adaptability - only about the various "polymorphs" of CharacterString - as a type, they simply allow different representations of the string, and as instances, all those representations (in different languages, scripts; or with internal structure) should all convey the same meaning. A person's name should not be "interpreted" as something else because it is structured into multiple parts.

**Comment by ronaldtse** [comment]
> For example, I don't think the use of polymorphism to describe software is required in the definition in ISO 19115 

I agree.

However, I am a bit hesitant to say "polymorphism is data". The examples given in ISO 19115-3 are about data structure inheritance. i.e. two classes share a superclass, the data structure/behavior specified by the superclass is preserved across the polymorphs.

Maybe "polymorphism on data structure" makes more sense to me?

Now I think this is a pretty good description of what we are trying to express:
> polymorphism for the situation where the data (about a concept/thing/feature instance/...) can be expressed in different ways for different purposes

However,
> A person's name should not be "interpreted" as something else because it is structured into multiple parts.

A person's name should always be considered a name. However, given a formatted full name vs a structured name with name parts, there is a clear semantic (hence interpretation) difference between "full name" and "surname" -- they are different. In this sense, only the semantics defined by the superclass is preserved, but the semantics defined by the instance classes are not -- which leads to the "polymorphic" characteristic, where the higher-level (intent) semantics are preserved, but not lower-level (details) semantics differ.

Something like this?
* characteristic of data in alternative forms that preserves semantics, structure and behavior, while allowing the extension of them

**Comment by ronaldtse** [comment]
From WG 7 meeting today:

characteristic that allows alternative forms that preserves semantics, structure and behavior, while allowing the extension of them

NOTE: Polymorphism is commonly used so that data can be better used for different usages and contexts.

Add sentence to document:
* In this document, polymorphism refers to its application to data.

**Comment by ronaldtse** [comment]
This definition is now in ISO 19115-3 and therefore closing.
