### ISSUE TITLE
ISO 19119 definition of 'entity' not in GeoLexica

### ISSUE THREAD

**Issue by PeterParslow** [ISO-TC211/StandardsTracker#515]
https://isotc211.geolexica.org/concepts/1948/ shows the entry in ISO 19148 for entity, which cites ISO 19119:2016.  ISO 19119:2016 does indeed define the term 'entity', and that entry appears in the 'current terms' tab of the Terminology Spreadsheet (as at 20240417), row 798. So why does it not have an entry in GeoLexica?

Note: ISO/DIS 19135 uses the same term for a specialisation of the concept to apply to persons/organisations. The DIS currently contains a distinct definition "independent person, group, body, party or organization" (as opposed to ISO 19119's more general "something that has separate and distinct existence and objective or conceptual reality"). I have noted this in a comment to ISO/DIS 19135.

**Comment by ReesePlews** [comment]
hello @PeterParslow thank you for the comment.

there is only [one entry in geolexica](https://isotc211.geolexica.org/concepts/1948/) for the term "entity" , shown below:

![image](https://github.com/user-attachments/assets/f778468d-c22d-430a-b969-e1b77cba6734)

the geolexica entry correctly references the ISO 19119 entry, as confirmed by the OPB entry, shown below:

![image](https://github.com/user-attachments/assets/e55881e3-7051-4aa1-911b-648169ada2c7)

note the OBP search lists only one entry in TC211 for the term/concept "entity", coming from ISO 19119:2016, 4.1.6

i am not sure what you mean by: 

> shows the entry in ISO 19148 for entity

as there is no terminological entry for "entity" in ISO 19148.

since ISO/DIS 19135 is currently in ballot i will not mention that here. 

regarding this question:

> So why does it not have an entry in GeoLexica?

it is important to note that Geolexica only contains English terms from published standards, along with translations of those English terms into various languages, graciously supported by the work of the TC211 national bodies. that is why the entry from ISO/DIS 19135 is presently not in Geolexica, and only in the terminology spreadsheet.

in the version of the terminology spreadsheet you listed, both terms are present, term-ids 1948 and 
2958 (CD 19135 added 2023-01-20). also note in the spreadsheet the record for term-id 2958 has been flagged as a possible harmonization issue.

a new version of the terminology spreadsheet will be released to members before the autumn plenary meeting.

let me know if there is anything else, if the answers above are suitable to resolve your question, please comment and close the issue.  thank you.

**Comment by PeterParslow** [comment]
My mistake: I misread the identifier "1948" as a reference (of sorts) to ISO 19148.
(Background: I was reviewing ISO/DIS 19135, recognised the definition of 'identifier' but was surprised to find that ISO/DIS 19135 doesn't cite a source - actually, for any of it's identifiers!)

**Comment by ReesePlews** [comment]
thanks @PeterParslow many of the terms originate in 19135 so no source references, while other terms, with correct source references are listed in clause 3 when required.  i am looking at the ballot draft and seeing the "appropriate" number of source references, so not a document generate issue.  TMG will also be processing the terms from ISO/DIS 19135 into the TMG repository but not until after the autumn plenary and commenting then. thanks.
